# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  username: <%= ENV.fetch("MYSQL_USER") { 5 } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { 5 } %>
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8

development:
  <<: *default
  database: identity-reconcilation

test:
  <<: *default
  database: identity-reconcilation-test

